sudo: required
services:
  - docker

#
# series of commands to run before running tests
#

# -t  for tagging image you can name it anything

before_install:
  - docker build -t singhadev01/docker-react2 -f Dockerfile.dev .

#
# series of command to run as part of test suite
# if u get status code !=0  then travis assum test failed

# override default run command with npm run test or yarn test
script:
  - docker run -e CI=true singhadev01/docker-react2 yarn test
