# Use an existing image as base
FROM node:alpine


#  if target directory does not exist it will be created
WORKDIR /app

# COPY local package.json 
COPY ./package.json  .

# download and install dependency
RUN npm install

# COPY index.js into container image. so we can  do rebuild just for changes in index.js
COPY . .

# Tell image what to do when it starts as container
CMD ["npm", "run", "start"]
